In [1]:
import torch
import random

In [3]:
a = torch.randn(3,3)
b = a > 0
indices = b.nonzero()#.squeeze()


In [57]:
logits = torch.randn(3,3,4)
y_soft = logits.softmax(dim=-1)
index = y_soft.topk(2, dim=-1)[1]
value = y_soft.max(-1, keepdim=True)[0]
y_hard = torch.zeros_like(logits, memory_format=torch.legacy_contiguous_format).scatter_(-1, index, 1.0)
print(index)
print(value)

tensor([[[2, 1],
         [0, 2],
         [1, 3]],

        [[3, 2],
         [3, 0],
         [3, 0]],

        [[2, 0],
         [1, 0],
         [0, 3]]])
tensor([[[0.7402],
         [0.6753],
         [0.3644]],

        [[0.3227],
         [0.3129],
         [0.4645]],

        [[0.5255],
         [0.3059],
         [0.3555]]])


In [62]:
print(y_soft)
a = y_soft > value*0.5
print(a)
a.float()

tensor([[[0.0131, 0.1310, 0.7402, 0.1157],
         [0.6753, 0.0072, 0.2931, 0.0244],
         [0.2938, 0.3644, 0.0451, 0.2967]],

        [[0.2521, 0.1295, 0.2957, 0.3227],
         [0.2718, 0.1828, 0.2324, 0.3129],
         [0.3022, 0.1450, 0.0884, 0.4645]],

        [[0.1806, 0.1308, 0.5255, 0.1632],
         [0.2589, 0.3059, 0.2028, 0.2325],
         [0.3555, 0.2058, 0.1942, 0.2445]]])
tensor([[[False, False,  True, False],
         [ True, False, False, False],
         [ True,  True, False,  True]],

        [[ True, False,  True,  True],
         [ True,  True,  True,  True],
         [ True, False, False,  True]],

        [[False, False,  True, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]])


tensor([[[0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [1., 1., 0., 1.]],

        [[1., 0., 1., 1.],
         [1., 1., 1., 1.],
         [1., 0., 0., 1.]],

        [[0., 0., 1., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [38]:

for i in range(len(index)):
    idx = [index[i][1]]
    if logits[i][idx] < 1:
        y_hard[i][index[i][1]] = 0
print(y_hard)

IndexError: index 3 is out of bounds for dimension 0 with size 3