In [3]:
import torch
import random
import numpy as np

In [3]:
a = torch.randn(3,3)
b = a > 0
indices = b.nonzero()#.squeeze()


In [57]:
logits = torch.randn(3,3,4)
y_soft = logits.softmax(dim=-1)
index = y_soft.topk(2, dim=-1)[1]
value = y_soft.max(-1, keepdim=True)[0]
y_hard = torch.zeros_like(logits, memory_format=torch.legacy_contiguous_format).scatter_(-1, index, 1.0)
print(index)
print(value)

tensor([[[2, 1],
         [0, 2],
         [1, 3]],

        [[3, 2],
         [3, 0],
         [3, 0]],

        [[2, 0],
         [1, 0],
         [0, 3]]])
tensor([[[0.7402],
         [0.6753],
         [0.3644]],

        [[0.3227],
         [0.3129],
         [0.4645]],

        [[0.5255],
         [0.3059],
         [0.3555]]])


In [62]:
print(y_soft)
a = y_soft > value*0.5
print(a)
a.float()

tensor([[[0.0131, 0.1310, 0.7402, 0.1157],
         [0.6753, 0.0072, 0.2931, 0.0244],
         [0.2938, 0.3644, 0.0451, 0.2967]],

        [[0.2521, 0.1295, 0.2957, 0.3227],
         [0.2718, 0.1828, 0.2324, 0.3129],
         [0.3022, 0.1450, 0.0884, 0.4645]],

        [[0.1806, 0.1308, 0.5255, 0.1632],
         [0.2589, 0.3059, 0.2028, 0.2325],
         [0.3555, 0.2058, 0.1942, 0.2445]]])
tensor([[[False, False,  True, False],
         [ True, False, False, False],
         [ True,  True, False,  True]],

        [[ True, False,  True,  True],
         [ True,  True,  True,  True],
         [ True, False, False,  True]],

        [[False, False,  True, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]])


tensor([[[0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [1., 1., 0., 1.]],

        [[1., 0., 1., 1.],
         [1., 1., 1., 1.],
         [1., 0., 0., 1.]],

        [[0., 0., 1., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [24]:
sbp = torch.ones(3)
dbp = torch.ones(3)
ppg = torch.randn(3, 3)
max_1 = 10
min_1 = 3
print(sbp)
print(dbp)
ppg

tensor([1., 1., 1.])
tensor([1., 1., 1.])


tensor([[-0.9314,  0.2716,  0.4498],
        [ 0.7469,  1.5423, -0.2700],
        [-0.6776,  0.7892, -1.2002]])

In [25]:
sbp = (sbp - 80) / (200 - 80)
sbp = sbp * (max_1 - min_1) + min_1

dbp = (dbp - 40) / (120 - 40)
dbp = dbp * (max_1 - min_1) + min_1
ppg = np.asarray(ppg)
ppg = (ppg - ppg.min(axis=0)) / (ppg.max(axis=0) - ppg.min(axis=0))
ppg = ppg * (max_1 - min_1) + min_1
ppg = list(ppg)


In [26]:
dbp

tensor([-0.4125, -0.4125, -0.4125])

In [28]:
((dbp - min_1)/(max_1 - min_1))*(120 - 40) + 40

tensor([1., 1., 1.])

In [82]:
a = torch.ones(1000, 64, 512)
b = torch.randn(512,838,1000)
a*b


RuntimeError: The size of tensor a (512) must match the size of tensor b (1000) at non-singleton dimension 2