In [3]:
import torch
import random
import numpy as np

In [3]:
a = torch.randn(3,3)
b = a > 0
indices = b.nonzero()#.squeeze()


In [57]:
logits = torch.randn(3,3,4)
y_soft = logits.softmax(dim=-1)
index = y_soft.topk(2, dim=-1)[1]
value = y_soft.max(-1, keepdim=True)[0]
y_hard = torch.zeros_like(logits, memory_format=torch.legacy_contiguous_format).scatter_(-1, index, 1.0)
print(index)
print(value)

tensor([[[2, 1],
         [0, 2],
         [1, 3]],

        [[3, 2],
         [3, 0],
         [3, 0]],

        [[2, 0],
         [1, 0],
         [0, 3]]])
tensor([[[0.7402],
         [0.6753],
         [0.3644]],

        [[0.3227],
         [0.3129],
         [0.4645]],

        [[0.5255],
         [0.3059],
         [0.3555]]])


In [62]:
print(y_soft)
a = y_soft > value*0.5
print(a)
a.float()

tensor([[[0.0131, 0.1310, 0.7402, 0.1157],
         [0.6753, 0.0072, 0.2931, 0.0244],
         [0.2938, 0.3644, 0.0451, 0.2967]],

        [[0.2521, 0.1295, 0.2957, 0.3227],
         [0.2718, 0.1828, 0.2324, 0.3129],
         [0.3022, 0.1450, 0.0884, 0.4645]],

        [[0.1806, 0.1308, 0.5255, 0.1632],
         [0.2589, 0.3059, 0.2028, 0.2325],
         [0.3555, 0.2058, 0.1942, 0.2445]]])
tensor([[[False, False,  True, False],
         [ True, False, False, False],
         [ True,  True, False,  True]],

        [[ True, False,  True,  True],
         [ True,  True,  True,  True],
         [ True, False, False,  True]],

        [[False, False,  True, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]])


tensor([[[0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [1., 1., 0., 1.]],

        [[1., 0., 1., 1.],
         [1., 1., 1., 1.],
         [1., 0., 0., 1.]],

        [[0., 0., 1., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [24]:
sbp = torch.ones(3)
dbp = torch.ones(3)
ppg = torch.randn(3, 3)
max_1 = 10
min_1 = 3
print(sbp)
print(dbp)
ppg

tensor([1., 1., 1.])
tensor([1., 1., 1.])


tensor([[-0.9314,  0.2716,  0.4498],
        [ 0.7469,  1.5423, -0.2700],
        [-0.6776,  0.7892, -1.2002]])

In [25]:
sbp = (sbp - 80) / (200 - 80)
sbp = sbp * (max_1 - min_1) + min_1

dbp = (dbp - 40) / (120 - 40)
dbp = dbp * (max_1 - min_1) + min_1
ppg = np.asarray(ppg)
ppg = (ppg - ppg.min(axis=0)) / (ppg.max(axis=0) - ppg.min(axis=0))
ppg = ppg * (max_1 - min_1) + min_1
ppg = list(ppg)


In [26]:
dbp

tensor([-0.4125, -0.4125, -0.4125])

In [28]:
((dbp - min_1)/(max_1 - min_1))*(120 - 40) + 40

tensor([1., 1., 1.])

In [1]:
import torch


In [4]:
a  = torch.load('/mlainas/KGPrompt_data/caltech101/conceptnet_features_base_level_1.pkl')
b  = torch.load('/mlainas/KGPrompt_data/caltech101/conceptnet_features_new_level_1.pkl')


In [13]:
print(b[0])

tensor([[ 0.3512, -0.2571,  0.0895,  ..., -0.1764,  0.0388, -0.1695],
        [ 0.4097, -0.2108, -0.1824,  ..., -0.0009, -0.0123, -0.2831],
        [ 0.4012, -0.0606, -0.1637,  ..., -0.1044, -0.0629, -0.2031],
        ...,
        [ 0.4401, -0.2917, -0.2820,  ..., -0.0432, -0.0208, -0.2655],
        [ 0.5822, -0.0846, -0.0883,  ..., -0.3387,  0.1965, -0.3042],
        [ 0.3385, -0.2852, -0.1259,  ...,  0.0056, -0.0608, -0.2638]],
       device='cuda:0')


In [14]:
print(a[0])

tensor([[ 0.3004,  0.1277,  0.3497,  ..., -0.0447,  0.1225,  0.2192],
        [ 0.2646,  0.2540,  0.2494,  ...,  0.0823,  0.0213,  0.2368],
        [ 0.1843,  0.2713,  0.4256,  ...,  0.0716,  0.2817,  0.3423],
        ...,
        [ 0.3845,  0.1630,  0.1449,  ...,  0.1173,  0.1097,  0.2165],
        [ 0.1293,  0.1477,  0.2824,  ...,  0.1987,  0.4356,  0.1067],
        [ 0.3148,  0.1912,  0.1919,  ...,  0.1452,  0.0693,  0.1838]],
       device='cuda:0')
